# -*- coding: utf-8 -*-
"""Cópia de Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SMJ1W2Pm8TDvn9YrB2hpxhRKwXPOLRxe

Leitura de dados
<https://raw.githubusercontent.com/VaniaMuniz/dados/master/dataRevisao.csv>
"""

import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/VaniaMuniz/dados/master/dataRevisao_xxxx.csv', delimiter=';')

data.head()

data.shape

data[['Quantidade de credito']]

data.sort_values('Quantidade de credito')

data.sort_values('Quantidade de credito', ascending=False).head(3)